name: Discord notify composite
description: Simple composite action to send a discord webhook message
inputs:
  webhook:
    description: 'Discord webhook URL (use secret)'
    required: true
  status:
    description: 'success|failure|info'
    required: true
  title:
    description: 'Title for embed'
    required: true
  body:
    description: 'Body/description for embed'
    required: true
runs:
  using: composite
  steps:
    - name: Send Discord notification
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook }}
        STATUS: ${{ inputs.status }}
        TITLE: ${{ inputs.title }}
        BODY: ${{ inputs.body }}
      run: |
        # Determine color based on status
        case "$STATUS" in
          success)
            COLOR=3066993  # Green
            ;;
          failure)
            COLOR=15158332  # Red
            ;;
          *)
            COLOR=9807270   # Orange
            ;;
        esac
        
        # Send to Discord
        curl -X POST "$WEBHOOK_URL" \
          -H 'Content-Type: application/json' \
          -d "{
            \"embeds\": [{
              \"title\": \"$TITLE\",
              \"description\": \"$BODY\",
              \"color\": $COLOR,
              \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
            }]
          }"
